# Generated by Django 3.0.4 on 2020-04-05 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('info', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Universe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='universes', to='pages.Team')),
            ],
            options={
                'unique_together': {('name', 'team')},
            },
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('info', models.CharField(max_length=255)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='systems', to='pages.Team')),
                ('universe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='systems', to='pages.Universe')),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('Up', 'Up'), ('Down', 'Down')], default='Up', max_length=255)),
                ('tag', models.CharField(choices=[('Operational', 'Operational'), ('Tests', 'Tests')], default='Operational', max_length=255)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servers', to='pages.Base')),
                ('systems', models.ManyToManyField(related_name='servers', to='pages.System')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servers', to='pages.Team')),
            ],
        ),
    ]
