# Generated by Django 3.0.4 on 2020-03-29 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('info', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('info', models.CharField(max_length=255)),
                ('universe', models.CharField(choices=[('IP', 'Ip'), ('Badid', 'Badid')], default='IP', max_length=255)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='systems', to='pages.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('base', models.CharField(choices=[('Yarkon', 'Yarkon'), ('Mifkada', 'Mifkada')], default='Yarkon', max_length=255)),
                ('status', models.CharField(choices=[('Up', 'Up'), ('Down', 'Down')], default='Up', max_length=255)),
                ('tag', models.CharField(choices=[('Operational', 'Operational'), ('Tests', 'Tests')], default='Operational', max_length=255)),
                ('ram', models.IntegerField()),
                ('cores', models.IntegerField()),
                ('systems', models.ManyToManyField(related_name='servers', to='pages.System')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servers', to='pages.Team')),
            ],
        ),
    ]
