# Generated by Django 3.0.4 on 2020-04-01 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='cores',
        ),
        migrations.RemoveField(
            model_name='server',
            name='ram',
        ),
    ]
