# Generated by Django 3.0.4 on 2020-03-29 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='team',
            field=models.CharField(max_length=255),
        ),
    ]
