[tool.poetry]
name = "data-sender"
version = "0.1.0"
description = ""
authors = ["Ophir Taieb"]

[tool.poetry.dependencies]
python = "^3.8"
paramiko = "^2.7.1"
graphyte = "^1.6.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
